// src/reportes/dashboardConfig.js
//
// Configuración declarativa del Dashboard Gerencial.
// Agregar un KPI nuevo = agregar un objeto aquí. No se tocan componentes.
//
// Cada KPI apunta a un campo de una vista resumen (vista_dashboard_<area>).
// Esas vistas son las que hacen el trabajo pesado en la base de datos;
// el frontend solo lee números ya calculados.

// ---------------------------------------------------------------------------
// Registro de áreas (alimenta tanto las secciones del Dashboard Gerencial
// como, más adelante, el menú lateral de Reportes por módulo)
// ---------------------------------------------------------------------------
export const AREAS = {
  ventas:     { label: 'Ventas',     icon: 'ti-trending-up',         orden: 1 },
  produccion: { label: 'Producción', icon: 'ti-building-factory-2',  orden: 2 },
  finanzas:   { label: 'Finanzas',   icon: 'ti-currency-dollar',     orden: 3 },
  empleados:  { label: 'Empleados',  icon: 'ti-users',               orden: 4 },
  compras:    { label: 'Compras',    icon: 'ti-shopping-cart',       orden: 5 },
  inventario: { label: 'Inventario', icon: 'ti-boxes',               orden: 6 },
  calidad:    { label: 'Calidad',    icon: 'ti-clipboard-check',     orden: 7 },
};

// ---------------------------------------------------------------------------
// Tipos de KPI soportados por <KPICard />
//   kpi_simple  -> un número (con o sin comparativo de período)
//   kpi_top     -> "el que más" (producto, cliente, proveedor, vendedor)
//   kpi_lista   -> mini ranking (top 3-5)
//   kpi_alerta  -> cuenta con semáforo/umbral (ej. próximos a vencer)
// ---------------------------------------------------------------------------

export const dashboardConfig = [

  // ======================= VENTAS =======================
  {
    id: 'ventas_dia',
    area: 'ventas',
    label: 'Ventas del día',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_ventas', campo: 'total_dia' },
    comparativo: { activo: true, contra: 'dia_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_ventas_detalle', filtroDefault: { periodo: 'hoy' } },
    orden: 1,
    cache: { ttlMinutos: 2 },
  },
  {
    id: 'ventas_mes',
    area: 'ventas',
    label: 'Ventas del mes',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_ventas', campo: 'total_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_ventas_detalle', filtroDefault: { periodo: 'mes' } },
    orden: 2,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'producto_mas_vendido',
    area: 'ventas',
    label: 'Producto más vendido',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_ventas_top_productos', campoNombre: 'producto', campoValor: 'cantidad_vendida' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_ventas_top_productos' },
    orden: 3,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'cliente_top',
    area: 'ventas',
    label: 'Cliente que más compra',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_ventas_top_clientes', campoNombre: 'cliente', campoValor: 'total_comprado' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_ventas_top_clientes' },
    orden: 4,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'vendedor_top',
    area: 'ventas',
    label: 'Vendedor con mayores ventas',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_ventas_top_vendedores', campoNombre: 'vendedor', campoValor: 'total_vendido' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_ventas_top_vendedores' },
    orden: 5,
    cache: { ttlMinutos: 30 },
  },

  // ======================= PRODUCCIÓN =======================
  {
    id: 'produccion_dia',
    area: 'produccion',
    label: 'Producción del día',
    tipo: 'kpi_simple',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_produccion', campo: 'kg_producidos_dia' },
    comparativo: { activo: true, contra: 'dia_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_produccion_detalle', filtroDefault: { periodo: 'hoy' } },
    orden: 1,
    cache: { ttlMinutos: 5 },
  },
  {
    id: 'rendimiento_promedio',
    area: 'produccion',
    label: 'Rendimiento promedio',
    tipo: 'kpi_simple',
    formato: 'porcentaje',
    fuente: { vista: 'vista_dashboard_produccion', campo: 'rendimiento_promedio' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: { condicion: 'menor_que', umbral: 85, mensaje: 'Rendimiento por debajo del objetivo' },
    drilldown: { tipo: 'grafico', vista: 'vista_dashboard_produccion_rendimiento_serie' },
    orden: 2,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'merma',
    area: 'produccion',
    label: 'Merma',
    tipo: 'kpi_simple',
    formato: 'porcentaje',
    fuente: { vista: 'vista_dashboard_produccion', campo: 'merma_promedio' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: { condicion: 'mayor_que', umbral: 5, mensaje: 'Merma por encima del objetivo' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_produccion_merma_detalle' },
    orden: 3,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'productos_elaborados',
    area: 'produccion',
    label: 'Productos elaborados',
    tipo: 'kpi_simple',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_produccion', campo: 'productos_elaborados_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_produccion_por_producto' },
    orden: 4,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'costos_produccion',
    area: 'produccion',
    label: 'Costos de producción',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_produccion', campo: 'costo_total_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'grafico', vista: 'vista_dashboard_produccion_costos_serie' },
    orden: 5,
    cache: { ttlMinutos: 30 },
  },

  // ======================= INVENTARIO =======================
  {
    id: 'stock_disponible',
    area: 'inventario',
    label: 'Stock disponible',
    tipo: 'kpi_simple',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_inventario', campo: 'stock_total' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_inventario_detalle' },
    orden: 1,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'productos_por_agotar',
    area: 'inventario',
    label: 'Productos próximos a agotarse',
    tipo: 'kpi_alerta',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_inventario', campo: 'cantidad_stock_bajo' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay productos por debajo del stock mínimo' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_inventario_stock_bajo' },
    orden: 2,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'productos_vencidos',
    area: 'inventario',
    label: 'Productos vencidos',
    tipo: 'kpi_alerta',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_inventario', campo: 'cantidad_vencidos' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay lotes vencidos en inventario' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_inventario_vencidos' },
    orden: 3,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'lotes_por_vencer',
    area: 'inventario',
    label: 'Lotes próximos a vencer',
    tipo: 'kpi_alerta',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_inventario', campo: 'cantidad_por_vencer' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay lotes por vencer en los próximos días' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_inventario_por_vencer' },
    orden: 4,
    cache: { ttlMinutos: 15 },
  },

  // ======================= FINANZAS =======================
  {
    id: 'caja_actual',
    area: 'finanzas',
    label: 'Caja actual',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'saldo_caja' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_finanzas_movimientos' },
    orden: 1,
    cache: { ttlMinutos: 2 },
  },
  {
    id: 'ingresos_mes',
    area: 'finanzas',
    label: 'Ingresos',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'ingresos_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'grafico', vista: 'vista_dashboard_finanzas_ingresos_serie' },
    orden: 2,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'egresos_mes',
    area: 'finanzas',
    label: 'Egresos',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'egresos_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'grafico', vista: 'vista_dashboard_finanzas_egresos_serie' },
    orden: 3,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'utilidad',
    area: 'finanzas',
    label: 'Utilidad',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'utilidad_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: { condicion: 'menor_que', umbral: 0, mensaje: 'Utilidad negativa este mes' },
    drilldown: { tipo: 'grafico', vista: 'vista_dashboard_finanzas_utilidad_serie' },
    orden: 4,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'cuentas_por_cobrar',
    area: 'finanzas',
    label: 'Cuentas por cobrar',
    tipo: 'kpi_alerta',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'total_cxc_vencido' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay cuentas por cobrar vencidas' },
    drilldown: { tipo: 'tabla', vista: 'vista_cuentas_por_cobrar' },
    orden: 5,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'cuentas_por_pagar',
    area: 'finanzas',
    label: 'Cuentas por pagar',
    tipo: 'kpi_alerta',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_finanzas', campo: 'total_cxp_pendiente' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay cuentas por pagar pendientes' },
    drilldown: { tipo: 'tabla', vista: 'vista_cuentas_por_pagar' },
    orden: 6,
    cache: { ttlMinutos: 10 },
  },

  // ======================= COMPRAS =======================
  {
    id: 'compras_mes',
    area: 'compras',
    label: 'Compras del mes',
    tipo: 'kpi_simple',
    formato: 'moneda',
    fuente: { vista: 'vista_dashboard_compras', campo: 'total_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_compras_detalle' },
    orden: 1,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'materia_prima_top',
    area: 'compras',
    label: 'Materia prima más comprada',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_compras_top_materia_prima', campoNombre: 'producto', campoValor: 'cantidad_comprada' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_compras_top_materia_prima' },
    orden: 2,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'insumo_top',
    area: 'compras',
    label: 'Insumo más comprado',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_compras_top_insumos', campoNombre: 'producto', campoValor: 'cantidad_comprada' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_compras_top_insumos' },
    orden: 3,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'proveedor_top',
    area: 'compras',
    label: 'Proveedor con mayor volumen',
    tipo: 'kpi_top',
    formato: 'texto',
    fuente: { vista: 'vista_dashboard_compras_top_proveedores', campoNombre: 'proveedor', campoValor: 'total_comprado' },
    comparativo: { activo: false },
    alerta: null,
    drilldown: { tipo: 'ranking', vista: 'vista_dashboard_compras_top_proveedores' },
    orden: 4,
    cache: { ttlMinutos: 30 },
  },

  // ======================= CALIDAD =======================
  {
    id: 'producciones_aprobadas',
    area: 'calidad',
    label: 'Producciones aprobadas',
    tipo: 'kpi_simple',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_calidad', campo: 'aprobadas_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_calidad_producciones', filtroDefault: { estado: 'aprobada' } },
    orden: 1,
    cache: { ttlMinutos: 15 },
  },
  {
    id: 'producciones_rechazadas',
    area: 'calidad',
    label: 'Producciones rechazadas',
    tipo: 'kpi_alerta',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_calidad', campo: 'rechazadas_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay producciones rechazadas este mes' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_calidad_producciones', filtroDefault: { estado: 'rechazada' } },
    orden: 2,
    cache: { ttlMinutos: 10 },
  },
  {
    id: 'mantenimientos_realizados',
    area: 'calidad',
    label: 'Mantenimientos realizados',
    tipo: 'kpi_simple',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_calidad', campo: 'mantenimientos_mes' },
    comparativo: { activo: true, contra: 'mes_anterior' },
    alerta: null,
    drilldown: { tipo: 'tabla', vista: 'mantenimientos' },
    orden: 3,
    cache: { ttlMinutos: 30 },
  },
  {
    id: 'controles_pendientes',
    area: 'calidad',
    label: 'Controles de calidad pendientes',
    tipo: 'kpi_alerta',
    formato: 'numero',
    fuente: { vista: 'vista_dashboard_calidad', campo: 'controles_pendientes' },
    comparativo: { activo: false },
    alerta: { condicion: 'mayor_que', umbral: 0, mensaje: 'Hay controles de calidad pendientes' },
    drilldown: { tipo: 'tabla', vista: 'vista_dashboard_calidad_controles_pendientes' },
    orden: 4,
    cache: { ttlMinutos: 10 },
  },
];

// ---------------------------------------------------------------------------
// Helper: agrupa la config por área, ya ordenada — es lo que va a consumir
// directamente el componente <Dashboard />
// ---------------------------------------------------------------------------
export function agruparPorArea() {
  return Object.keys(AREAS)
    .sort((a, b) => AREAS[a].orden - AREAS[b].orden)
    .map((areaKey) => ({
      area: areaKey,
      ...AREAS[areaKey],
      kpis: dashboardConfig
        .filter((k) => k.area === areaKey)
        .sort((a, b) => a.orden - b.orden),
    }));
}